//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активні.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Діє з.
        /// </summary>
        internal static string ActiveFrom {
            get {
                return ResourceManager.GetString("ActiveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити чек.
        /// </summary>
        internal static string AddCheck {
            get {
                return ResourceManager.GetString("AddCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати домівку.
        /// </summary>
        internal static string AddHome {
            get {
                return ResourceManager.GetString("AddHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додатковий тариф.
        /// </summary>
        internal static string AdditionalFee {
            get {
                return ResourceManager.GetString("AdditionalFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва додаткового платежу.
        /// </summary>
        internal static string AdditionalFeeName {
            get {
                return ResourceManager.GetString("AdditionalFeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додаткові фіксовані платежі.
        /// </summary>
        internal static string AdditionalFixedPayments {
            get {
                return ResourceManager.GetString("AdditionalFixedPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додаткові платежі за лічільником.
        /// </summary>
        internal static string AdditionalMetersPayments {
            get {
                return ResourceManager.GetString("AdditionalMetersPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати послугу.
        /// </summary>
        internal static string AddService {
            get {
                return ResourceManager.GetString("AddService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати тариф.
        /// </summary>
        internal static string AddTariff {
            get {
                return ResourceManager.GetString("AddTariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі роки.
        /// </summary>
        internal static string AllYears {
            get {
                return ResourceManager.GetString("AllYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квартира.
        /// </summary>
        internal static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комунальні платежі.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площа.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будинок.
        /// </summary>
        internal static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За площею.
        /// </summary>
        internal static string ByArea {
            get {
                return ResourceManager.GetString("ByArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не фіксовані платежі.
        /// </summary>
        internal static string ByYear_ByCost {
            get {
                return ResourceManager.GetString("ByYear_ByCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За обсягом спожитого.
        /// </summary>
        internal static string ByYear_WithMeasures {
            get {
                return ResourceManager.GetString("ByYear_WithMeasures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відміна.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви дійсно хочете видалити цей чек? Цей процес не можна скасувати..
        /// </summary>
        internal static string CheckDeleteConfirmation {
            get {
                return ResourceManager.GetString("CheckDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при видаленні чеку {0} з будинку {1}. {2}.
        /// </summary>
        internal static string CheckDeletedError {
            get {
                return ResourceManager.GetString("CheckDeletedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чек за {0} з будинку {1} видалено.
        /// </summary>
        internal static string CheckDeletedOk {
            get {
                return ResourceManager.GetString("CheckDeletedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рахунок за.
        /// </summary>
        internal static string CheckFor {
            get {
                return ResourceManager.GetString("CheckFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місто.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви дійсно хочете деактивувати тариф?.
        /// </summary>
        internal static string ConfirmTariffDeactivation {
            get {
                return ResourceManager.GetString("ConfirmTariffDeactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати новий тариф на основі того, що деактивується?.
        /// </summary>
        internal static string ConfirmTariffDeactivationAddNew {
            get {
                return ResourceManager.GetString("ConfirmTariffDeactivationAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Щоб підтвердити дію, введіть останній день дії тарифу та підтвердіть деактивацію.
        /// </summary>
        internal static string ConfirmTariffDeactivationHelp {
            get {
                return ResourceManager.GetString("ConfirmTariffDeactivationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спожитий обсяг.
        /// </summary>
        internal static string ConsumedVolume {
            get {
                return ResourceManager.GetString("ConsumedVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скопіювати.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зображення завантажено.
        /// </summary>
        internal static string CopyDownloadOk {
            get {
                return ResourceManager.GetString("CopyDownloadOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зображення скопійовано в буфер обміну.
        /// </summary>
        internal static string CopyOk {
            get {
                return ResourceManager.GetString("CopyOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вартість.
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Країна.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточне.
        /// </summary>
        internal static string CurrentMeasure {
            get {
                return ResourceManager.GetString("CurrentMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточний показник лічільника.
        /// </summary>
        internal static string CurrentMeasureFull {
            get {
                return ResourceManager.GetString("CurrentMeasureFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви справді хочете видалити цю домівку? Всі пов&apos;язані тарифи та рахунки також будуть видалені. Цей процес не можна скасувати..
        /// </summary>
        internal static string DeleteHomeConfirmation {
            get {
                return ResourceManager.GetString("DeleteHomeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви дійсно хочете видалити цей тариф? Усі пов&apos;язані рахунки також будуть видалені. Можливо, краще деактивуйте цей тариф. Процес видалення неможливо скасувати..
        /// </summary>
        internal static string DeleteTariffConfirmation {
            get {
                return ResourceManager.GetString("DeleteTariffConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обсяг.
        /// </summary>
        internal static string Difference {
            get {
                return ResourceManager.GetString("Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деактивувати.
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неактивні.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активувати.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата кінця.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва фіксованого платежу.
        /// </summary>
        internal static string FixedPayName {
            get {
                return ResourceManager.GetString("FixedPayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to одиницю виміру.
        /// </summary>
        internal static string ForUnit {
            get {
                return ResourceManager.GetString("ForUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальні.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти до налаштувань.
        /// </summary>
        internal static string GoToSettings {
            get {
                return ResourceManager.GetString("GoToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домівка.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домівка {0} додана.
        /// </summary>
        internal static string HomeAddedOk {
            get {
                return ResourceManager.GetString("HomeAddedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вдалося видалити домівку {0}. Помилка: {1}.
        /// </summary>
        internal static string HomeDeletedError {
            get {
                return ResourceManager.GetString("HomeDeletedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домівку {0} видалено.
        /// </summary>
        internal static string HomeDeletedOk {
            get {
                return ResourceManager.GetString("HomeDeletedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домівки.
        /// </summary>
        internal static string Homes {
            get {
                return ResourceManager.GetString("Homes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Встановити за замовчуванням.
        /// </summary>
        internal static string HomeSetAsDefault {
            get {
                return ResourceManager.GetString("HomeSetAsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви впевнені, що хочете встановити {0} як свою домівку за замовчуванням?.
        /// </summary>
        internal static string HomeSetAsDefaultConfirmation {
            get {
                return ResourceManager.GetString("HomeSetAsDefaultConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вдалося встановити домівку {0} як за замовчуванням. Помилка: {1}.
        /// </summary>
        internal static string HomeSetAsDefaultError {
            get {
                return ResourceManager.GetString("HomeSetAsDefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домівка {0} була встановлена ​​як за замовчуванням.
        /// </summary>
        internal static string HomeSetAsDefaultOk {
            get {
                return ResourceManager.GetString("HomeSetAsDefaultOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домівка {0} оновлена.
        /// </summary>
        internal static string HomeUpdatedOk {
            get {
                return ResourceManager.GetString("HomeUpdatedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За замовчуванням.
        /// </summary>
        internal static string IsDefault {
            get {
                return ResourceManager.GetString("IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ліміти.
        /// </summary>
        internal static string Limits {
            get {
                return ResourceManager.GetString("Limits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Споживання за усі роки.
        /// </summary>
        internal static string MetersByAllYears {
            get {
                return ResourceManager.GetString("MetersByAllYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Споживання за {0} рік.
        /// </summary>
        internal static string MetersByYear {
            get {
                return ResourceManager.GetString("MetersByYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показники лічільників.
        /// </summary>
        internal static string MetersMeasurements {
            get {
                return ResourceManager.GetString("MetersMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місяць.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В системі не знайдено будинку за замовчанням. Створіть або оберіть його в налаштуваннях і спробуйте знову..
        /// </summary>
        internal static string NoDefaultHome {
            get {
                return ResourceManager.GetString("NoDefaultHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домівки не знайдено. Будь ласка, перевірте налаштування.
        /// </summary>
        internal static string NoHomes {
            get {
                return ResourceManager.GetString("NoHomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У цьому домогосподарстві нема жодного тарифу. Для того, щоб почати роботу, додайте тарифи в налаштуваннях..
        /// </summary>
        internal static string NoTariffs {
            get {
                return ResourceManager.GetString("NoTariffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У цьому домогосподарстві нема жодного тарифу для {0} . Для того, щоб почати роботу, додайте тарифи в налаштуваннях..
        /// </summary>
        internal static string NoTariffsForDate {
            get {
                return ResourceManager.GetString("NoTariffsForDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не фіксовані послуги за всі роки.
        /// </summary>
        internal static string NotFixedByAllYears {
            get {
                return ResourceManager.GetString("NotFixedByAllYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не фіксовані послуги за {0} рік.
        /// </summary>
        internal static string NotFixedByYear {
            get {
                return ResourceManager.GetString("NotFixedByYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не фіксовані послуги.
        /// </summary>
        internal static string NotFixedPayments {
            get {
                return ResourceManager.GetString("NotFixedPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ок.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата оплати.
        /// </summary>
        internal static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показати:.
        /// </summary>
        internal static string PerPage {
            get {
                return ResourceManager.GetString("PerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попереднє.
        /// </summary>
        internal static string PreviousMeasure {
            get {
                return ResourceManager.GetString("PreviousMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ціна.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ціна вище ліміту.
        /// </summary>
        internal static string PriceOverLimit {
            get {
                return ResourceManager.GetString("PriceOverLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Область.
        /// </summary>
        internal static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перезавантажити.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мова.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть послугу.
        /// </summary>
        internal static string SelectService {
            get {
                return ResourceManager.GetString("SelectService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть тип тарифу.
        /// </summary>
        internal static string SelectTariffType {
            get {
                return ResourceManager.GetString("SelectTariffType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Послуга.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Послуги.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to кв.м..
        /// </summary>
        internal static string Sqm {
            get {
                return ResourceManager.GetString("Sqm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата початку.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вулиця.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сума.
        /// </summary>
        internal static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тариф {0} створено.
        /// </summary>
        internal static string TariffAddedOk {
            get {
                return ResourceManager.GetString("TariffAddedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вдалося видалити тариф {0}. Помилка: {1}.
        /// </summary>
        internal static string TariffDeletedError {
            get {
                return ResourceManager.GetString("TariffDeletedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тариф {0} ({1}) видалено.
        /// </summary>
        internal static string TariffDeletedOk {
            get {
                return ResourceManager.GetString("TariffDeletedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тарифи.
        /// </summary>
        internal static string Tariffs {
            get {
                return ResourceManager.GetString("Tariffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фіксований.
        /// </summary>
        internal static string TariffType_Fixed {
            get {
                return ResourceManager.GetString("TariffType.Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фіксована сума кожен місяць.
        /// </summary>
        internal static string TariffType_Fixed_Tooltip {
            get {
                return ResourceManager.GetString("TariffType.Fixed.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За площею.
        /// </summary>
        internal static string TariffType_HouseHoldArea {
            get {
                return ResourceManager.GetString("TariffType.HouseHoldArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сума залежить від площі помешкання.
        /// </summary>
        internal static string TariffType_HouseHoldArea_Tooltip {
            get {
                return ResourceManager.GetString("TariffType.HouseHoldArea.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лічильник.
        /// </summary>
        internal static string TariffType_Meters {
            get {
                return ResourceManager.GetString("TariffType.Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сума залежить від показників лічільника.
        /// </summary>
        internal static string TariffType_Meters_Tooltip {
            get {
                return ResourceManager.GetString("TariffType.Meters.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не фіксований.
        /// </summary>
        internal static string TariffType_NotFixedPayment {
            get {
                return ResourceManager.GetString("TariffType.NotFixedPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довільна сума кожен місяць.
        /// </summary>
        internal static string TariffType_NotFixedPayment_Tooltip {
            get {
                return ResourceManager.GetString("TariffType.NotFixedPayment.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За обсягом.
        /// </summary>
        internal static string TariffType_Volume {
            get {
                return ResourceManager.GetString("TariffType.Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сума залежить від обсягу спожитої послуги, без введення показників лічільника.
        /// </summary>
        internal static string TariffType_Volume_Tooltip {
            get {
                return ResourceManager.GetString("TariffType.Volume.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тариф {0} оновлено.
        /// </summary>
        internal static string TariffUpdatedOk {
            get {
                return ResourceManager.GetString("TariffUpdatedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тарифи на сьогодні.
        /// </summary>
        internal static string TodaysTariffs {
            get {
                return ResourceManager.GetString("TodaysTariffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всього до оплати: {0} послуг.
        /// </summary>
        internal static string TotalServicesFivePlus {
            get {
                return ResourceManager.GetString("TotalServicesFivePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всього до оплати: {0} послуга.
        /// </summary>
        internal static string TotalServicesOne {
            get {
                return ResourceManager.GetString("TotalServicesOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всього до оплати: {0} послуги.
        /// </summary>
        internal static string TotalServicesTwoFour {
            get {
                return ResourceManager.GetString("TotalServicesTwoFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виникла непердбачувана помилка..
        /// </summary>
        internal static string UnhandledError {
            get {
                return ResourceManager.GetString("UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одиниці вимірювання.
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оновити.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верхній ліміт.
        /// </summary>
        internal static string UpperLimit {
            get {
                return ResourceManager.GetString("UpperLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додатковий платіж за {0}.
        /// </summary>
        internal static string UseAdditionalFeeLabel {
            get {
                return ResourceManager.GetString("UseAdditionalFeeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додатковий фіксований платіж.
        /// </summary>
        internal static string UseFixedPayLabel {
            get {
                return ResourceManager.GetString("UseFixedPayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Використовувати ліміти.
        /// </summary>
        internal static string UseLimits {
            get {
                return ResourceManager.GetString("UseLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} по місяцях.
        /// </summary>
        internal static string UtilitiesByMonth {
            get {
                return ResourceManager.GetString("UtilitiesByMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви дійсно хочете видалити цю послугу? Усі тарифи, та чеки, які її використовують, будуть видалені. Цю дію неможливо відмінити..
        /// </summary>
        internal static string UtilitiesDeleteConfirmation {
            get {
                return ResourceManager.GetString("UtilitiesDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Послуга {0} видалена.
        /// </summary>
        internal static string UtilitiesDeleteError {
            get {
                return ResourceManager.GetString("UtilitiesDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при видаленні {0}: {1}.
        /// </summary>
        internal static string UtilitiesDeleteOk {
            get {
                return ResourceManager.GetString("UtilitiesDeleteOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилки.
        /// </summary>
        internal static string ValidationSummary {
            get {
                return ResourceManager.GetString("ValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to поживання за обсягом спожитого за всі роки.
        /// </summary>
        internal static string VolumeByAllYears {
            get {
                return ResourceManager.GetString("VolumeByAllYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to поживання за обсягом спожитого за {0} рік.
        /// </summary>
        internal static string VolumeByYear {
            get {
                return ResourceManager.GetString("VolumeByYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платежі за обсягом спожитого.
        /// </summary>
        internal static string VolumePayments {
            get {
                return ResourceManager.GetString("VolumePayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нульовий чек.
        /// </summary>
        internal static string ZeroCheck {
            get {
                return ResourceManager.GetString("ZeroCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Використовується для актуалізації показників без прорахунку вартості..
        /// </summary>
        internal static string ZeroCheckDescription {
            get {
                return ResourceManager.GetString("ZeroCheckDescription", resourceCulture);
            }
        }
    }
}
